Adding struct packed array support for ports
steveicarus/iverilog pull request #506
Opened 2021-05-04 08:35 UTC by phhorrein

This is another simple pull request to add support for packed array with struct base type in module ports.

2022-02-02 01:44 UTC, steveicarus commented
Can you rebase this to the current tip of "master", and add a test suite example to demonstrate and test it? We have reworked out continuous integration works in the iverilog repository, and rebasing will get this PR onto continuous integration. The PR otherwise looks fine, so it would be great to get it into the regular flow.

2022-03-27 18:33 UTC, phhorrein commented
Yes, I will do that as soon as I find some time, probably in a few days/weeks.

Le 2 février 2022 02:44:18 GMT+01:00, Stephen Williams ***@***.***> a écrit :
>Can you rebase this to the current tip of "master", and add a test suite example to demonstrate and test it? We have reworked out continuous integration works in the iverilog repository, and rebasing will get this PR onto continuous integration. The PR otherwise looks fine, so it would be great to get it into the regular flow.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/steveicarus/iverilog/pull/506#issuecomment-1027496452
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

2022-07-30 18:52 UTC, steveicarus requested changes
This PR no longer merges, so it needs to be rebased, and conflicts resolved.

Also, we need with this PR a regression test program that demonstrates the problem, and shows that this PR fixes it. That test program should be included in the regression test suite. If you need help with that, at least produce the program and we can give you guidance on how to include it in the CI test suite.

2022-08-02 07:56 UTC, larsclausen commented
I think this got resolved as part of bbe44deec2f4c0ba and can be closed.

2022-12-11 23:51 UTC, closed without merging